baseURL = "https://raphg.me"
languageCode = "en-us"
theme = "aafu"
summaryLength = "10"
paginate = 6

[permalinks]
post = "/:title/"

[params]
    title = "Portfolio"
    author = "Raphaele Guillemot"
    description = ""
    keywords = "web developer, developer, digital artist, creative media, artist"

    [params.theme]
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "main"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = false
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Raphaele Guillemot"
		    tagline = "Web Developer | Digital Artist"
		    location = "Hong Kong"
        photo = "avatar.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa fa-id-card"
            url = "/raphaeleg.vcf"
            title = "VCF"
        [[params.social.list]]
            class = "fab"
            icon = "fa fa-envelope"
            url = "mailto:raphaeleguillemotmichelle AT gmail DOT com"
            title = "Gmail"
        [[params.social.list]]
            class = "fab"
            icon = "fa fa-rss"
            url = "/index.xml"
            title = "Subscribe (RSS)"
        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin"
            url = "https://www.linkedin.com/in/raphaele-guillemot-6a34271a8/"
            title = "LinkedIn"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "I'm a French-Chinese born in 2002 and aspiring to be a video game designer. The aim of this site is to showcase all my creative processes and results."

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Head Artist"
            dates = "2020 - *Present*"
            link = "tags/issia"
            company = "the Inter-School Social Issues Association (ISSIA) newspaper"
        [[params.experience.list]]
            position = "Head Artist"
            dates = "2019 - 2020"
            link = "tags/the-victorian"
            company = "The School Newspaper Club (The Victorian)"
            details = "Promoted as Hear Artist after four years of team participation (front pages, article related art, comics, etc...)"
        [[params.experience.list]]
            position = "Artist"
            dates = "2019"
            link = "tags/blood-drive"
            company = "The School Blood Drive Commitee"
            details = "Created advertisement posters to promote the 2019 Blood Donation school event"
        [[params.experience.list]]
            position = "Head of Advertisement"
            dates = "2017 - 2019"
            company = "Family Fun Day Coffee Shop"
        [[params.experience.list]]
            position = "Head Editor"
            dates = "2017 - 2020"
            link = "tags/campus-tv"
            company = "The School Video Production Club (Campus TV)"
        [[params.experience.list]]
            position = "Podcast Editor"
            dates = "2020 - *Present*"
            company = "ISSIA"

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "Visual Arts"
            college = "IBDP Program"
            thesis_link = "tags/ibdp-visual-arts-hl"
            dates = "2018 - 2020"
        [[params.education.list]]
            degree = "Creative Multi-media Illustration program"
            college = "HKDI"
            dates = "2016 - 2017"
        [[params.education.list]]
            degree = "Code Apps with C++"
            college = "iD Tech Summer Program"
            thesis_link = "program/text-adventure-game/"
            dates = "July 2017"
        [[params.education.list]]
            degree = "Web Development"
            college = "First Code Academy"
            dates = "2017 - 2019"
        [[params.education.list]]
            degree = "University Mathematics I"
            college = "HKU Summer Institute"
            dates = "July 2019"

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "2018「Movie Character Created By Me」- Video Competition"
            url = "/production/a-geraniums-journey/"
            description = "Semi-Finalist (out of 1500 videos) hosted by the Hong Kong Playground Association"
        [[params.project.list]]
            title = "2019 'Supporting Mothers’ Breastfeeding Journey' Secondary School Short Video Competition"
            url = "/production/breastfeeding-stigma/"
            description = "Merit award and certificate"
        [[params.project.list]]
            title = "Digital Chess"
            url = "/program/-chess/"
            description = "Created Digital Chess by scratch to showcase knowledge in jQuery"
        [[params.project.list]]
            title = "HK Flower Show Drawing Competition"
            description = "Participated in the 2019 HK Flower Show Jockey Club Student Drawing Competition"

    # Skill section
    [params.hobby]
        title = "Skills"
        icon = "fas fa-cogs"

        [[params.hobby.list]]
		    hobby = "Self-Taught Digital Art since 2010"
        [[params.hobby.list]]
		    hobby = "Self-Taught Adobe After Effects since 2016"
        [[params.hobby.list]]
		    hobby = "Trained in Web Development Languages (HTML, CSS, JavaScript, JQuery, JSON, HTML5)"
        [[params.hobby.list]]
		    hobby = "Self-Taught Adobe Audition since 2020"
        [[params.hobby.list]]
		    hobby = "Knowledge on Python, C# and C++"
